CREATE TABLE autores (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL,
  data_nascimento TIMESTAMP NOT NULL,
  biografia VARCHAR(300) NOT NULL,
  data_criacao TIMESTAMP NOT NULL
)
